### ISSUE TITLE
Broken device registration implementation

### ISSUE THREAD

**Issue by japesinator** [btoews/softu2f-legacy-driver#2]
This is a low severity functionality issue in `UserPresence::test`. In case the active tab changes before the Security Key Request appears, the former is never presented to the user.

To reproduce the issue, register a new device on the [yubico website](https://demo.yubico.com/u2f?tab=register), then immediately switch to a new tab.
The Security Key Request does not show up, despite the fact that the “Performing U2F action” is present once you return to the registration tab. This does not occur when users attempt to login to using the [login tab](https://demo.yubico.com/u2f?tab=login), in which case the Security
Key Request shows up as expected. 

## Affected components:
`UserPresence`’s [`test`](https://github.com/mastahyeti/SoftU2FTool/blob/master/SoftU2FTool/UserPresence.swift#L25) routine.

**Comment by btoews** [comment]
I don't think this is an issue with SoftU2F. Running the app from the console you can see debugging output of what HID frames are sent/received. Here's the steps I followed and what I saw:

- I opened Yubico [demo registration page](https://demo.yubico.com/u2f?tab=register) in two separate Chrome tabs.
- In the first tab I entered credentials, submitted the form, and quickly switched to the other tab. At this point SoftU2F hadn't sent or received any HID frames.
- In the second tab I entered credentials and submitted the form. There was some hid traffic, the test-of-user-presence was displayed, I clicked through, and there was more HID traffic.
- I returned to the first tab. The page said "Performing U2F action", but no HID traffic was sent/received.

I also tried this with a Yubikey and saw the same behavior. I'm pretty sure this is a Chrome behavior, so I'm closing the issue. Feel free to reopen if I'm misunderstanding. Thanks.
