### ISSUE TITLE
Unchecked terminate() return values

### ISSUE THREAD

**Issue by japesinator** [btoews/softu2f-legacy-driver#4]
This is a low-severity code quality issue in SoftU2FDriver.cpp. In SoftU2FDriver.cpp, `terminate` is called, however, the respective return value is not checked. In cases where a client is still attached to the device, this will fail silently.

Affected components:
[SoftU2FDriver.cpp:L46](https://github.com/mastahyeti/SoftU2F/blob/c70e796dffc4d2a86052afa313f06eb14bbfc976/SoftU2F/SoftU2FDriver.cpp#L46)
[SoftU2FDriver.cpp:L139](https://github.com/mastahyeti/SoftU2F/blob/c70e796dffc4d2a86052afa313f06eb14bbfc976/SoftU2F/SoftU2FDriver.cpp#L139)

## Recommendation:
Add check for the return value of termination like in SoftU2FUserClient.cpp, or utilize [`isInactive`](https://developer.apple.com/documentation/kernel/ioservice/1810198-isinactive?language=objc) to not call `terminate` on a device that is already inactive

## References:
https://developer.apple.com/documentation/kernel/ioservice/1811110-terminate

**Comment by btoews** [comment]
Fixed by d363fb6
