### ISSUE TITLE
Consistency in error handling

### ISSUE THREAD

**Issue by nettrino** [btoews/softu2f-legacy-driver#5]
This is a low-severity code quality issue. 

Resources are not always released in an order inverse to their creation (e.g.,  [`destroyUserClientDevice`](https://github.com/mastahyeti/SoftU2F/blob/master/SoftU2F/SoftU2FDriver.cpp#L128) and [`userClientDevice`](https://github.com/mastahyeti/SoftU2F/blob/master/SoftU2F/SoftU2FDriver.cpp#L96) release `key` and `device` in inverse orders. This might potentially have unwanted consequences in case the code gets modified in the future.

Moreover the return value of functions that may fail is not consistently checked  (e.g., [`userClientDevice`](https://github.com/mastahyeti/SoftU2F/blob/master/SoftU2F/SoftU2FDriver.cpp#L115) the return value of `start` is not checked)

## Recommendation:

Resources should be freed in an order reverse to their creation. Moreover, single `goto` labels can be replaced with multiple labels as in:

```
if (!key)
  goto fail_key;

device = OSDynamicCast(SoftU2FDeviceClassName, m_hid_devices->getObject(key));
if (!device)
  goto fail_device;

...
fail_device:
  if (device)
    device->release();
fail_key:
  if (key)
    key->release();
  return false;
}
```

**Comment by btoews** [comment]
Fixed by f872a59 and 2d9624f.
