### ISSUE TITLE
Uninitialized com_github_SoftU2FUserClient::notifyFrame

### ISSUE THREAD

**Issue by nettrino** [btoews/softu2f-legacy-driver#7]
There is a medium-severity kernel information disclosure vulnerability in com_github_SoftU2FUserClient::notifyFrame. It might cause the disclosure of kernel memory to a user space application.

The asyncReferenceCount field in IOExternalMethodArgument should be validated and used when copying data from the asyncReference field. When this is not performed, out of bounds reads may occur from the asyncReference buffer.

## Affected components:
[com_github_SoftU2FUserClient::notifyFrame](https://github.com/mastahyeti/SoftU2F/blob/master/SoftU2F/SoftU2FUserClient.cpp#L165)

## Recommendation:
We suggest two changes:
Add `bzero(fNotifyRef,sizeof(OSAsyncReference64));`
Instead of sizeof(OSAsyncReference64), only copy `sizeof(io_user_reference_t)* arguments->asyncReferenceCount` bytes instead.

**Comment by btoews** [comment]
Nice find. Is it possible for `arguments->asyncReferenceCount` to be more than 8, or would the call to `IOConnectCallAsyncScalarMethod` fail? I'm wondering if it might be simpler to just fail if `arguments->asyncReferenceCount` is anything other than what we expect, just to be cautious. Something like https://github.com/mastahyeti/SoftU2F/commit/0ce2fb8e66030094de5e3c15566f71948538ff24.

**Comment by computerality** [comment]
The max is 8, the kernel APIs won't allow anything higher than that through at all. Catching the error there is fine.

**Comment by btoews** [comment]
> The max is 8, the kernel APIs won't allow anything higher than that through at all.

Cool. Out of curiosity, did you figure that out by trial and error? The docs are virtually nonexistent for all this stuff.

**Comment by computerality** [comment]
Reading the kernel source code is how I figured out this one.
